### ISSUE TITLE
 😒😒😒

### ISSUE THREAD

**Issue by 00110000** [Noiwex/luadev#13]
Buenas noches, ladies, and mentlegen (xD). 

I have been perusing through the human-readable instructions located within this source control repository. To my shock and dismay, I have stumbled upon a sundry of erroneous uses of the pronoun "who". The reality, to be frank, is that the overwhelming majority of these should be instead substituted with "whom".

Please, someone of strong character must create a pull request to correct this injustice.

**Comment by 00110000** [comment]
+1

**Comment by 54** [comment]
plus 1 bro

**Comment by 54** [comment]
? is this thing on

**Comment by idubs** [comment]
I support this

**Comment by 54** [comment]
See #14

**Comment by 00110000** [comment]
THANK YOU!!!
