### ISSUE TITLE
Error if trying to table.Copy(_G)

### ISSUE THREAD

**Issue by CoolGoga** [Noiwex/luadev#18]
Luadev is erroring when i try to table.Copy(_G)

```
[ERROR] addons/luadev-master/lua/autorun/easylua.lua:758: attempt to call a nil value
stack traceback:
	addons/luadev-master/lua/autorun/easylua.lua:758: in function '__newindex'
	lua/includes/extensions/table.lua:31: in function 'Copy'
	lua/includes/extensions/table.lua:38: in function 'Copy'
	Черэшня<luadev>:1: in main chunk
	[C]: in function 'LUADEV_EXECUTE_FUNCTION'
addons/luadev-master/lua/autorun/easylua.lua:758: attempt to call a nil value
```

**Comment by Noiwex** [comment]
I'm afraid you can't do that given how easylua and table.Copy work. Besides, why would you need to copy whole _G table?

**Comment by CoolGoga** [comment]
I need it for prevent detouring functions. Yes, i can just localise libs instead of copy _G, but it's easier to copy everything. Okay, i will use second option.

**Comment by Python1320** [comment]
setfenv(1,_G) in front of script to disable easylua
