### ISSUE TITLE
Chat Commands

### ISSUE THREAD

**Issue by looterz** [Noiwex/luadev#7]
Would be very useful to be able to enable some chat command shortcuts to the existing console commands via cvar.

```
~send<env> <code>
~run<env> <code>
```

etc.

**Comment by Noiwex** [comment]
I don't think it's up to me to implement chat commands.

**Comment by looterz** [comment]
Oh, looks like there is some support already in  luadev/lua/autorun/server/luadev_chatcmds.lua , but it depends on a library named aowl. Should be easy enough to throw an else statement in there and set them up manually with a playersay hook.
